<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Version>1.0.0</Version>
		<Authors>OpenEugene</Authors>
		<Company>OpenEugene</Company>
		<Description>LittleHelpBook</Description>
		<Product>OpenEugene.LittleHelpBook</Product>
		<Copyright>OpenEugene</Copyright>
		<AssemblyName>OpenEugene.Module.LittleHelpBook.Client.Oqtane</AssemblyName>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.1" />
		<PackageReference Include="MudBlazor" Version="8.5.1" />
		<PackageReference Include="Oqtane.Client" Version="6.0.1" />
		<PackageReference Include="Oqtane.Shared" Version="6.0.1" />
		<PackageReference Include="System.Net.Http.Json" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="9.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shared\LittleHelpBook.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Oqtane.Client"></Reference>
		<Reference Include="Oqtane.Shared"></Reference>
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Modules\PhoneNumber\Edit.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="Modules\PhoneNumber\Index.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="Modules\PhoneNumber\Settings.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	</ItemGroup>

	<PropertyGroup>
		<!-- there may be other elements here -->
		<BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

</Project>
